[package]
name = "pr-check"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Checks pull requests against contributing criteria"
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
askama.workspace = true
chrono.workspace = true
clap.workspace = true
github-repo.workspace = true
futures-util.workspace = true
reqwest.workspace = true
serde.workspace = true
serde-saphyr.workspace = true
tokio.workspace = true
