site_name: 'Awesome Static Analysis'
site_url: 'https://matthias-endler.de/awesome-static-analysis/'
site_description: 'A curated list of linters, code quality checkers, and other static analysis tools  for various programming languages'
site_author: 'Matthias Endler'
repo_name: 'mre/awesome-static-analysis/'
repo_url: 'https://github.com/mre/awesome-static-analysis/'
theme: 'material'
extra:
  feature:
    tabs: false
  palette:
    primary: 'red'
    accent: 'pink'
  social:
    - type: 'github'
      link: 'https://github.com/mre'
    - type: 'twitter'
      link: 'https://twitter.com/matthiasendler'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/matthiasendler'
google_analytics:
  - 'UA-693428-1'
  - 'auto'
extra_css:
  - css/extra.css
markdown_extensions:
    - toc:
