name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Runs every Thursday at 20:23 GMT to avoid bit rot
    - cron: "20 23 * * 4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Render list
        run: make render
