name: Check Links

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
      working-directory: ci
    - name: Run tests
      run: cargo test --verbose
      working-directory: ci
