name: "Close stale issues"
on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity in the last 60 days. It will be closed in 7 days if no further activity occurs.
            Thank you for your contributions.
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: stale
